require('dotenv/config')
const app = require('express')()
const bodyParser = require('body-parser')
const cors = require('cors')
const routes = require('./app/routes')

app.use(cors())
app.use(bodyParser.json())
app.use(routes)
app.listen(process.env.APP_PORT)